adding mycd

diff --git a/file_checks_profile b/file_checks_profile
--- a/file_checks_profile
+++ b/file_checks_profile
@@ -77,3 +77,24 @@ is_dir()
   fi
 }
 #####################################################################
+is_dir_writeable()
+{ 
+  if [[ $# -eq 1 ]]; then
+    temp_file="temp_file_$(ts)"
+    touch ${1}/${temp_file}
+    if [[ $? -eq 0 ]]; then
+      rm ${temp_file}
+      true
+    else
+      false
+    fi
+  fi
+}
+#####################################################################
+mycd()
+{
+   if [[ $# -eq 1 ]]; then
+      is_dir $1 && { /usr/bin/cd $1 } || { echo "ERROR"; exit 1 }
+   fi
+}
+#####################################################################
