few updates

diff --git a/util_profile b/util_profile
--- a/util_profile
+++ b/util_profile
@@ -18,16 +18,16 @@ if [[ -f /etc/.file_checks_profile ]]; then source /etc/.file_checks_profile; fi
 ts(){ echo "$(date '+%Y%m%d_%H%M%S')"; }
 ####################################################################################
 check_for_error(){ 
-   if [[ "${ERROR}" == "true" || "${SUCCESS} == "false" ]]; then 
+   if [[ "${ERROR}" == "true" || "${SUCCESS}" == "false" ]]; then 
       echo "ERROR"
-	  exit 1
+      exit 1
    fi
 }
-is_error(){ if [[ "${ERROR}" == "true" || "${SUCCESS} == "false" ]]; then true; elif [[ "${ERROR}" == "false" || "${SUCCESS} == "true" ]]; then false; fi; }
-is_success(){ if [[ "${ERROR}" == "false" || "${SUCCESS} == "true" ]]; then true; elif [[ "${ERROR}" == "true" || "${SUCCESS} == "false" ]]; then false; fi; }
+is_error(){ if [[ "${ERROR}" == "true" || "${SUCCESS}" == "false" ]]; then true; elif [[ "${ERROR}" == "false" || "${SUCCESS}" == "true" ]]; then false; fi; }
+is_success(){ if [[ "${ERROR}" == "false" || "${SUCCESS}" == "true" ]]; then true; elif [[ "${ERROR}" == "true" || "${SUCCESS}" == "false" ]]; then false; fi; }
 
 # USAGE Info:
-# Let us try curl command to download yahoo home page.
+# Let us try curl command to download yahoo home page.e.
 # curl -k -f -s https://www.yahoo.com
 # is_ExitStatus $? "Download FAILED from yahoo" "Download from yahoo good"
 # First Arg - exit status of prev command
@@ -35,14 +35,14 @@ is_success(){ if [[ "${ERROR}" == "false" || "${SUCCESS} == "true" ]]; then true
 # Third Arg - Success notice - need to be within quotes
 is_ExitStatus()
 {
-  if [[ ${1} -ne 0 ]]; then
+  if [[ "${1}" -ne 0 ]]; then
      if [[ -n "${2}" ]]; then
          echo "ERROR: ${2}"
      else
          echo "ERROR: prev command failed"
      fi
   else
-     if [[ $# -eq 3 && -n "${3}" ]]; then
+     if [[ "$#" -eq 3 && -n "${3}" ]]; then
          echo "SUCCESS: ${3}"
      fi
   fi
@@ -57,7 +57,7 @@ is_ExitStatus()
 # Third Arg - Success notice - need to be within quotes
 check_ExitStatus()
 {
-  if [[ ${1} -ne 0 ]]; then
+  if [[ "${1}" -ne 0 ]]; then
      if [[ -n "${2}" ]]; then
          echo "ERROR: ${2}"
          exit 1
@@ -66,7 +66,7 @@ check_ExitStatus()
          exit 1
      fi
   else
-     if [[ $# -eq 3 && -n "${3}" ]]; then
+     if [[ "$#" -eq 3 && -n "${3}" ]]; then
          echo "SUCCESS: ${3}"
      fi
   fi
